server:
  port: 8000

spring:
  application:
    name: eureka-server

eureka:
  client:
    register-with-eureka: false
    fetch-register: false
    service-url:
      defaultZone: http://localhost:8000/eureka

